services:
  db:
    image: postgres:latest
    container_name: octopus_db
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: octopus
      POSTGRES_PASSWORD: octopus
      POSTGRES_DB: octopus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    env_file: .env
    network_mode: host
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0

volumes:
  postgres_data:
